---
- hosts: all
  tasks:

  - name: Create new local account
    ansible.windows.win_user:
      name: "{{ local_account_username }}"
      fullname: "{{ local_account_fullname }}"
      password: "{{ local_account_password }}"
      state: present
      update_password: on_create
      password_expired: true
      groups:
        - Remotedesktopbenutzer

  - name: Ensure {{ local_account_username }} does not exist
    win_user:
      name: "{{ local_account_username }}"
      state: absent