---
- hosts: all
  tasks:
    - name: create local user
      ansible.windows.win_user:
        name: "{{ local_account_username }}"
        password: "{{ local_account_password }}"
        groups: "Remotedesktopbenutzer"
        update_password: on_create
        password_expired: true